[package]
name = "letter-boxed"
version = "0.1.0"
edition = "2022"

[dependencies]
derivative = "2.2.0"
itertools = "0.12.0"
pathfinding = "4.8.2"
prefix_tree = {path = "../prefix-tree"}
regex = "1.10.3"
reqwest = { version = "0.11.23", features = ["blocking"] }
